### ISSUE TITLE
Illegal line in `inverseqft_n4`?

### ISSUE THREAD

**Issue by leofang** [pnnl/QASMBench#1]
Hello, I was testing our QASM parser and noticed that this line seems fishy:
https://github.com/pnnl/QASMBench/blob/8f06d4ff1a3e5f566cc9c05c1b3446918d772728/small/inverseqft_n4/inverseqft_n4.qasm#L9
All quantum and classical registers are already declared prior to this line, so it's unclear which `q` it refers to.

**Comment by uuudown** [comment]
Hi Leo, sorry for the late reply. This is not an error. OpenQASM standard allows using q to refer to the 4 qubits as defied in qreg q[4]. See page 5 of the spec https://arxiv.org/pdf/1707.03429.pdf. Thanks.
