### ISSUE TITLE
Duplicate declaration of gate

### ISSUE THREAD

**Issue by Sola85** [pnnl/QASMBench#2]
Some circuits, e.g. small/pea_n5.qasm cannot be read by the latest version of Qiskit (0.36.1) giving an error message 

`"Duplicate declaration for gate 'cu' at line 14, file .\nPrevious occurrence at line 144, file [...]/qiskit/qasm/libs/qelib1.inc"`

Could the offending gate in the qasm files be renamed, so that there is no name collision?

**Comment by uuudown** [comment]
Hi Sola85, thanks a lot for reporting this issue. This will be fixed in our next release in a week.

**Comment by uuudown** [comment]
This has been fixed in Version 1.4. Thanks!
